---
gems_install_path: "/home/user/.autoproj/gems"
prefer_indep_over_os_packages: false
osdeps_mode: all
reused_autoproj_installations: []
manifest_source:
  type: git
  url: https://github.com/esa-prl/buildconf.git
  push_to: git@github.com:esa-prl/buildconf.git
GITHUB: http
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: https://github.com
GITHUB_PRIVATE_ROOT: https://github.com
GITORIOUS: http
GITORIOUS_ROOT: https://git.gitorious.org
GITORIOUS_PUSH_ROOT: https://git.gitorious.org
GITORIOUS_PRIVATE_ROOT: https://git.gitorious.org
operating_system:
- - ubuntu
  - debian
- - '16.04'
  - 16.04.4
  - lts
  - xenial
  - xerus
  - default
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
cxx11: true
typelib_cxx_loader: castxml
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
